pipeline{
    agent none
    stages{
        stage('build'){
            agent {
                dockerfile true
                label 'build-slave'
            }
            steps{
                sh 'node --version'
            } 
         }
    }
}
