pipeline{
    agent none
    stages{
        stage('build'){
            agent {
                dockerfile{
                label 'build-slave'
                dir 'nodejsapp'
                }
            }
            steps{
                sh 'node --version'
            } 
         }
    }
}
